INSERT INTO tb_products (name, description, available_quantity, price) VALUES
('Caderno Universitário', 'Caderno com 200 folhas e capa dura', 120, 29.90),
('Caneta Esferográfica Azul', 'Caneta com ponta 1.0mm e grip emborrachado', 300, 2.50),
('Garrafa Térmica Inox 1L', 'Garrafa térmica com vedação a vácuo', 40, 89.90),
('Fone Bluetooth', 'Fone de ouvido sem fio com estojo carregador', 60, 149.00),
('Mouse Sem Fio', 'Mouse wireless com receptor USB e 2.4GHz', 100, 79.90),
('Impressora Multifuncional', 'Impressora jato de tinta com Wi-Fi e scanner', 20, 599.00),
('Smartphone Android', 'Celular com 128GB, câmera 48MP e Android 13', 15, 1899.99),
('Liquidificador 700W', 'Liquidificador 5 velocidades com copo de 2L', 25, 199.00),
('Pen Drive 64GB', 'Pen drive USB 3.0 com alta velocidade', 180, 39.90),
('Caixa de Som Bluetooth', 'Caixinha com bateria de 10h e som estéreo', 50, 129.90),
('Luminária de Mesa LED', 'Luminária com braço flexível e toque touch', 70, 89.00),
('Carregador Turbo USB-C', 'Carregador rápido com tecnologia PD', 90, 69.90),
('Tesoura Escolar', 'Tesoura com ponta arredondada para crianças', 150, 6.90),
('Mochila Executiva', 'Mochila com compartimento para notebook', 30, 159.00),
('Balança Digital', 'Balança de cozinha com precisão de 1g', 40, 59.00),
('Cabo HDMI 2m', 'Cabo HDMI 2.0 com suporte a 4K', 200, 24.90),
('Lixeira Inox 5L', 'Lixeira com pedal e acabamento em inox', 35, 79.90),
('Teclado Bluetooth', 'Teclado slim compatível com tablets e PCs', 55, 119.90),
('Relógio Smartwatch', 'Relógio com monitor cardíaco e notificações', 20, 229.90),
('Adaptador Tomada Universal', 'Adaptador de viagem para múltiplos países', 100, 49.90);
